version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: islam_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${DB_NAME:-islam_education}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - islam_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: islam_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: mongodb://admin:password123@mongodb:27017/islam_education?authSource=admin
      DB_NAME: ${DB_NAME:-islam_education}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - islam_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8001}
    container_name: islam_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8001}
    depends_on:
      - backend
    networks:
      - islam_network

  nginx:
    image: nginx:alpine
    container_name: islam_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./uploads:/usr/share/nginx/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - islam_network

volumes:
  mongodb_data:

networks:
  islam_network:
    driver: bridge